version: '3.4'

services:
  yolo_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        weights_file: yolo9000.weights
        config_file: data/yolo9000.cfg
        meta_file: data/combine9k.data
    volumes:
      - ./app.py:/app/app.py
    ports:
      - 8080:80
